# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            The Bitter Coffee
tagline:          Fun drawings by a diabetic!
url:              http://thebittercoffee.com
paginate:         1
baseurl:          /
author:
  name:           Ryan Sherlock
  url:            https://imsherlock.com/
  email:          ryan.m.sherlock@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           github.com/imsherlock/tbc.github.io
